name: Publish Barricade2
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - name: Build and publish to Maven
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          PGP_KEY_CONTENTS: ${{ secrets.PGP_KEY_CONTENTS }}
        run: ./gradlew publishReleasePublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository